env:
  contexts:
  - excludePaths: []
    name: baseline
    urls:
    - http://host.docker.internal:3200
  parameters:
    failOnError: true
    progressToStdout: false
jobs:
- parameters:
    enableTags: false
    maxAlertsPerRule: 10
  type: passiveScan-config
- parameters:
    maxDuration: 1
    url: http://host.docker.internal:3200
  type: spider
- parameters:
    maxDuration: 1
    url: http://host.docker.internal:3200
  type: spiderClient
- parameters:
    maxDuration: 0
  type: passiveScan-wait
- parameters:
    format: Long
    summaryFile: /home/zap/zap_out.json
  rules:
  - action: IGNORE
    customMessage: ''
    id: 10019
  - action: IGNORE
    customMessage: ''
    id: 10031
  - action: IGNORE
    customMessage: ''
    id: 10049
  - action: IGNORE
    customMessage: ''
    id: 10109
  - action: IGNORE
    customMessage: ''
    id: 10111
  - action: IGNORE
    customMessage: ''
    id: 10202
  type: outputSummary
- parameters:
    reportDescription: ''
    reportDir: /zap/wrk/
    reportFile: report/zap.html
    reportTitle: ZAP Scanning Report
    template: traditional-html
  type: report
- parameters:
    reportDescription: ''
    reportDir: /zap/wrk/
    reportFile: report/zap.json
    reportTitle: ZAP Scanning Report
    template: traditional-json
  type: report
