-- Quiz Night's seed bank: hand-checked questions, so a quiz runs with no AI at all (CI, and the scripted quiz master).
--
-- Every answer is backed by its source: the quote is the sentence fetched from that page (Wikipedia, or the image's
-- Wikimedia Commons page), read and checked against the answer, not written from memory. Picture questions use
-- public-domain images from Wikimedia Commons, copied into the quiz-images bucket under names made from a hash of
-- the image (so a name never gives the answer away); `supabase start` loads them from supabase/seed/storage.

insert into content.quiz_bank
  (topic, kind, difficulty, region, prompt, options, answer, unit, source_url, source_quote, image_path, image_credit)
values
  ($q$general$q$, $q$choice$q$, 1, null, $q$Which planet is known as the Red Planet?$q$, $q$["Venus", "Mars", "Jupiter", "Saturn"]$q$::jsonb, $q${"option": 1}$q$::jsonb, null, $q$https://en.wikipedia.org/wiki/Mars$q$, $q$It is also known as the "Red Planet", for its orange-red appearance.$q$, null, null),
  ($q$general$q$, $q$choice$q$, 1, null, $q$What is the largest ocean on Earth?$q$, $q$["Atlantic", "Indian", "Pacific", "Arctic"]$q$::jsonb, $q${"option": 2}$q$::jsonb, null, $q$https://en.wikipedia.org/wiki/Pacific_Ocean$q$, $q$The Pacific Ocean is the largest and deepest of Earth's five oceanic divisions.$q$, null, null),
  ($q$general$q$, $q$choice$q$, 2, null, $q$Which gas do plants take in from the air to make food by photosynthesis?$q$, $q$["Oxygen", "Carbon dioxide", "Nitrogen", "Hydrogen"]$q$::jsonb, $q${"option": 1}$q$::jsonb, null, $q$https://en.wikipedia.org/wiki/Photosynthesis$q$, $q$== Overview == Most photosynthetic organisms are photoautotrophs, which means that they are able to synthesize food directly from carbon dioxide and water using energy from light.$q$, null, null),
  ($q$general$q$, $q$true_false$q$, 2, null, $q$The Great Wall of China can be seen from the Moon with the naked eye.$q$, null, $q${"value": false}$q$::jsonb, null, $q$https://en.wikipedia.org/wiki/Great_Wall_of_China$q$, $q$=== From the Moon === The Great Wall of China cannot be seen by the naked human eye from the Moon which orbits around Earth at an average distance of 384,399 kilometres (238,854 mi).$q$, null, null),
  ($q$general$q$, $q$estimate$q$, 2, null, $q$How many bones are there in the adult human body?$q$, null, $q${"value": 206}$q$::jsonb, $q$bones$q$, $q$https://en.wikipedia.org/wiki/Human_skeleton$q$, $q$It is composed of around 270 bones at birth – this total decreases to around 206 bones by adulthood after some bones fuse together, not counting accessory bones.$q$, null, null),
  ($q$general$q$, $q$estimate$q$, 1, null, $q$In what year did people first land on the Moon?$q$, null, $q${"value": 1969}$q$::jsonb, null, $q$https://en.wikipedia.org/wiki/Apollo_11$q$, $q$Apollo 11 (July 16–24, 1969) was the American spaceflight that first landed humans on the Moon, and the fifth crewed mission of NASA's Apollo program.$q$, null, null),
  ($q$general$q$, $q$estimate$q$, 3, null, $q$How tall is Mount Everest, in metres?$q$, null, $q${"value": 8848.86}$q$::jsonb, $q$metres$q$, $q$https://en.wikipedia.org/wiki/Mount_Everest$q$, $q$Its height was most recently measured in 2020 through a joint survey by Nepalese and Chinese authorities as 8,848.86 m (29,031 ft 8+1⁄2 in).$q$, null, null),
  ($q$geography$q$, $q$choice$q$, 1, null, $q$What is the capital of Australia?$q$, $q$["Sydney", "Melbourne", "Canberra", "Perth"]$q$::jsonb, $q${"option": 2}$q$::jsonb, null, $q$https://en.wikipedia.org/wiki/Canberra$q$, $q$Canberra ( KAN-brə; Ngunawal: Kanbarra) is the capital city of Australia and the largest population centre in the Australian Capital Territory.$q$, null, null),
  ($q$geography$q$, $q$choice$q$, 1, null, $q$What is the capital of Canada?$q$, $q$["Toronto", "Ottawa", "Vancouver", "Montreal"]$q$::jsonb, $q${"option": 1}$q$::jsonb, null, $q$https://en.wikipedia.org/wiki/Ottawa$q$, $q$Ottawa ( , ; Canadian French: [ɔtawɑ] ) is the capital city of Canada.$q$, null, null),
  ($q$geography$q$, $q$choice$q$, 2, null, $q$Which is the largest hot desert in the world?$q$, $q$["Gobi", "Sahara", "Kalahari", "Thar"]$q$::jsonb, $q${"option": 1}$q$::jsonb, null, $q$https://en.wikipedia.org/wiki/Sahara$q$, $q$With an area of 9,200,000 square kilometres (3,600,000 sq mi), it is the largest hot desert in the world and the third-largest desert overall, smaller only than the deserts of Antarctica and the northern Arctic.$q$, null, null),
  ($q$geography$q$, $q$true_false$q$, 2, null, $q$Mount Kilimanjaro is in Kenya.$q$, null, $q${"value": false}$q$::jsonb, null, $q$https://en.wikipedia.org/wiki/Mount_Kilimanjaro$q$, $q$Mount Kilimanjaro () is a large dormant stratovolcano in Tanzania.$q$, null, null),
  ($q$geography$q$, $q$estimate$q$, 2, $q$IN$q$, $q$How many states does India have?$q$, null, $q${"value": 28}$q$::jsonb, $q$states$q$, $q$https://en.wikipedia.org/wiki/States_and_union_territories_of_India$q$, $q$India is a federal union comprising 28 states and 8 union territories, for a total of 36 subnational entities.$q$, null, null),
  ($q$science$q$, $q$choice$q$, 1, null, $q$What is the chemical symbol for gold?$q$, $q$["Ag", "Au", "Gd", "Go"]$q$::jsonb, $q${"option": 1}$q$::jsonb, null, $q$https://en.wikipedia.org/wiki/Gold$q$, $q$The symbol Au is from the Latin aurum 'gold'.$q$, null, null),
  ($q$science$q$, $q$choice$q$, 1, null, $q$Which planet is closest to the Sun?$q$, $q$["Venus", "Mercury", "Earth", "Mars"]$q$::jsonb, $q${"option": 1}$q$::jsonb, null, $q$https://en.wikipedia.org/wiki/Mercury_%28planet%29$q$, $q$Mercury is the first planet from the Sun and the smallest in the Solar System.$q$, null, null),
  ($q$science$q$, $q$true_false$q$, 1, null, $q$Bats are mammals.$q$, null, $q${"value": true}$q$::jsonb, null, $q$https://en.wikipedia.org/wiki/Bat$q$, $q$Bats (order Chiroptera ) are winged mammals, the only mammals capable of true and sustained flight.$q$, null, null),
  ($q$science$q$, $q$estimate$q$, 3, null, $q$How many elements are there on the periodic table?$q$, null, $q${"value": 118}$q$::jsonb, $q$elements$q$, $q$https://en.wikipedia.org/wiki/Periodic_table$q$, $q$By 2010, the first 118 elements were known, thereby completing the first seven rows of the table; however, chemical characterization is still needed for the heaviest elements to confirm that their properties match their positions.$q$, null, null),
  ($q$cricket$q$, $q$choice$q$, 1, null, $q$How many players does each cricket team have on the field?$q$, $q$["9", "10", "11", "12"]$q$::jsonb, $q${"option": 2}$q$::jsonb, null, $q$https://en.wikipedia.org/wiki/Cricket$q$, $q$Cricket is a bat-and-ball game that is played between two teams of eleven players on a field, at the centre of which is a 22-yard (20-metre; 66-foot) pitch with a wicket at each end, each comprising two bails (small sticks) balanced on three stumps.$q$, null, null),
  ($q$cricket$q$, $q$choice$q$, 2, null, $q$Who won the first Cricket World Cup, in 1975?$q$, $q$["England", "India", "West Indies", "Australia"]$q$::jsonb, $q${"option": 2}$q$::jsonb, null, $q$https://en.wikipedia.org/wiki/1975_Cricket_World_Cup$q$, $q$After Australia defeated England and the West Indies defeated New Zealand in the semi-finals, the West Indies which came into the tournament as favourites, defeated Australia in the final at Lord's by 17 runs to become the first World Cup winners.$q$, null, null),
  ($q$cricket$q$, $q$true_false$q$, 2, null, $q$A cricket pitch is 22 yards long.$q$, null, $q${"value": true}$q$::jsonb, null, $q$https://en.wikipedia.org/wiki/Cricket_pitch$q$, $q$It is 22 yd (20.12 m) long (1 chain) and 10 ft (3.05 m) wide.$q$, null, null),
  ($q$cricket$q$, $q$estimate$q$, 2, null, $q$In what year did India first win the Cricket World Cup?$q$, null, $q${"value": 1983}$q$::jsonb, null, $q$https://en.wikipedia.org/wiki/1983_Cricket_World_Cup$q$, $q$It was held from 9 to 25 June 1983 in England and Wales and was won by India.$q$, null, null),
  ($q$bollywood$q$, $q$choice$q$, 2, $q$IN$q$, $q$Who directed the 2001 film Lagaan?$q$, $q$["Karan Johar", "Ashutosh Gowariker", "Farhan Akhtar", "Rajkumar Hirani"]$q$::jsonb, $q${"option": 1}$q$::jsonb, null, $q$https://en.wikipedia.org/wiki/Lagaan$q$, $q$Land Tax) is a 2001 Indian Hindi-language epic period sports drama film written and directed by Ashutosh Gowariker.$q$, null, null),
  ($q$bollywood$q$, $q$true_false$q$, 2, $q$IN$q$, $q$Sholay was released in 1975.$q$, null, $q${"value": true}$q$::jsonb, null, $q$https://en.wikipedia.org/wiki/Sholay$q$, $q$'Embers') is a 1975 Indian Hindi-language action-adventure film directed by Ramesh Sippy, produced by his father G.$q$, null, null),
  ($q$bollywood$q$, $q$estimate$q$, 3, $q$IN$q$, $q$In what year was Mughal-e-Azam released?$q$, null, $q${"value": 1960}$q$::jsonb, null, $q$https://en.wikipedia.org/wiki/Mughal-e-Azam$q$, $q$The Great Mughal) is a 1960 Indian epic historical drama film produced and directed by K.$q$, null, null),
  ($q$bollywood$q$, $q$choice$q$, 1, $q$IN$q$, $q$Which 1995 film has Shah Rukh Khan as Raj and Kajol as Simran?$q$, $q$["Kuch Kuch Hota Hai", "Dilwale Dulhania Le Jayenge", "Kabhi Khushi Kabhie Gham", "Devdas"]$q$::jsonb, $q${"option": 1}$q$::jsonb, null, $q$https://en.wikipedia.org/wiki/Dilwale_Dulhania_Le_Jayenge$q$, $q$The film stars Shah Rukh Khan and Kajol as Raj and Simran, two young non-resident Indians, who fall in love during a vacation through Europe with their friends.$q$, null, null),
  ($q$food$q$, $q$choice$q$, 1, null, $q$Which country does paella come from?$q$, $q$["Italy", "Spain", "Mexico", "Portugal"]$q$::jsonb, $q${"option": 1}$q$::jsonb, null, $q$https://en.wikipedia.org/wiki/Paella$q$, $q$It is one of the best-known dishes in Spanish cuisine.$q$, null, null),
  ($q$food$q$, $q$choice$q$, 1, null, $q$What is the main ingredient of guacamole?$q$, $q$["Avocado", "Tomato", "Peas", "Cucumber"]$q$::jsonb, $q${"option": 0}$q$::jsonb, null, $q$https://en.wikipedia.org/wiki/Guacamole$q$, $q$Guacamole (Spanish: [ɡwakaˈmole] ), sometimes informally shortened to guac in the United States, is an avocado-based dip, spread, or salad first developed in Mexico.$q$, null, null),
  ($q$food$q$, $q$true_false$q$, 2, null, $q$Sushi rice is seasoned with vinegar.$q$, null, $q${"value": true}$q$::jsonb, null, $q$https://en.wikipedia.org/wiki/Sushi$q$, $q$Sushi (すし, 寿司, 鮨, 鮓; pronounced [sɯɕiꜜ] or [sɯꜜɕi] ) is a traditional Japanese dish made with vinegared rice (鮨飯, sushi-meshi), typically seasoned with sugar and salt, and combined with a variety of ingredients (ねた, neta), such as seafood, vegetables, or meat; raw seafood is the most common, although some may be cooked.$q$, null, null),
  ($q$music$q$, $q$choice$q$, 1, null, $q$How many keys does a standard modern piano have?$q$, $q$["76", "88", "92", "100"]$q$::jsonb, $q${"option": 1}$q$::jsonb, null, $q$https://en.wikipedia.org/wiki/Piano$q$, $q$Most modern pianos have 52 white keys and 36 black keys, for a total of 88 keys (seven octaves plus a minor third, from A0 to C8).$q$, null, null),
  ($q$music$q$, $q$choice$q$, 1, null, $q$Which band recorded Hey Jude?$q$, $q$["The Rolling Stones", "The Beatles", "Queen", "The Who"]$q$::jsonb, $q${"option": 1}$q$::jsonb, null, $q$https://en.wikipedia.org/wiki/Hey_Jude$q$, $q$"Hey Jude" is a song by the English rock band the Beatles that was released as a non-album single in August 1968.$q$, null, null),
  ($q$music$q$, $q$true_false$q$, 1, null, $q$A violin has four strings.$q$, null, $q${"value": true}$q$::jsonb, null, $q$https://en.wikipedia.org/wiki/Violin$q$, $q$Most violins have a hollow wooden body, and commonly have four strings (sometimes five), usually tuned in perfect fifths with notes G3, D4, A4, E5, and are most commonly played by drawing a bow across the strings.$q$, null, null),
  ($q$science$q$, $q$picture$q$, 1, null, $q$Which planet is this?$q$, $q$["Jupiter", "Saturn", "Uranus", "Neptune"]$q$::jsonb, $q${"option": 1}$q$::jsonb, null, $q$https://commons.wikimedia.org/wiki/File:Saturn_during_Equinox.jpg$q$, $q$This natural color view of the planet Saturn was created from images collected shortly after Cassini began its extended Equinox Mission in July 2008. (Saturn actually reached equinox on August 11, 2009.)$q$, $q$4b7ff46425c55aca4e31be89ee4c04c7.jpg$q$, $q${"author": "NASA / JPL / Space Science Institute", "licence": "Public domain", "source_url": "https://commons.wikimedia.org/wiki/File:Saturn_during_Equinox.jpg"}$q$::jsonb),
  ($q$science$q$, $q$picture$q$, 2, null, $q$Which planet is this?$q$, $q$["Mars", "Jupiter", "Saturn", "Neptune"]$q$::jsonb, $q${"option": 1}$q$::jsonb, null, $q$https://commons.wikimedia.org/wiki/File:Jupiter_and_its_shrunken_Great_Red_Spot.jpg$q$, $q$This full-disc image of Jupiter was taken on 21 April 2014 with Hubble's Wide Field Camera 3 (WFC3).$q$, $q$c40306b066f21da214e171f076aea57d.jpg$q$, $q${"author": "NASA, ESA, and A. Simon (Goddard Space Flight Center)", "licence": "Public domain", "source_url": "https://commons.wikimedia.org/wiki/File:Jupiter_and_its_shrunken_Great_Red_Spot.jpg"}$q$::jsonb),
  ($q$geography$q$, $q$picture$q$, 1, null, $q$Which country's flag is this?$q$, $q$["India", "Niger", "Ireland", "Italy"]$q$::jsonb, $q${"option": 0}$q$::jsonb, null, $q$https://commons.wikimedia.org/wiki/File:Flag_of_India.svg$q$, $q$The Flag of India. The colours are saffron, white and green. The navy blue wheel in the center of the flag has a diameter approximately the width of the white band and is called Ashoka's Dharma Chakra, with 24 spokes (after Ashoka, the Great). Each spoke depicts one hour of the day, portraying the prevalence of righteousness all 24 hours of it.$q$, $q$69074216b8dbaf8c382cd7a2dc941a3f.png$q$, $q${"author": "Government of India", "licence": "Public domain", "source_url": "https://commons.wikimedia.org/wiki/File:Flag_of_India.svg"}$q$::jsonb),
  ($q$geography$q$, $q$picture$q$, 1, null, $q$Which country's flag is this?$q$, $q$["Japan", "Bangladesh", "South Korea", "China"]$q$::jsonb, $q${"option": 0}$q$::jsonb, null, $q$https://commons.wikimedia.org/wiki/File:Flag_of_Japan.svg$q$, $q$Flag of Japan$q$, $q$4ab4211b473b0142e4a2a59eb2e4a042.png$q$, $q${"author": "Various", "licence": "Public domain", "source_url": "https://commons.wikimedia.org/wiki/File:Flag_of_Japan.svg"}$q$::jsonb),
  ($q$geography$q$, $q$picture$q$, 2, null, $q$Which country's flag is this?$q$, $q$["Portugal", "Brazil", "Colombia", "Argentina"]$q$::jsonb, $q${"option": 1}$q$::jsonb, null, $q$https://commons.wikimedia.org/wiki/File:Flag_of_Brazil.svg$q$, $q$Flag of Brazil$q$, $q$84214e962767c6984d91ace858c5a7c4.png$q$, $q${"author": "Raimundo Teixeira Mendes", "licence": "Public domain", "source_url": "https://commons.wikimedia.org/wiki/File:Flag_of_Brazil.svg"}$q$::jsonb),
  ($q$general$q$, $q$picture$q$, 1, null, $q$Who painted this?$q$, $q$["Michelangelo", "Leonardo da Vinci", "Raphael", "Rembrandt"]$q$::jsonb, $q${"option": 1}$q$::jsonb, null, $q$https://en.wikipedia.org/wiki/Mona_Lisa$q$, $q$The Mona Lisa is a half-length portrait painting by the Italian artist Leonardo da Vinci.$q$, $q$5f223c31ba0a477eb7cbe5e5f959d822.jpg$q$, $q${"author": "Leonardo da Vinci", "licence": "Public domain", "source_url": "https://commons.wikimedia.org/wiki/File:Mona_Lisa,_by_Leonardo_da_Vinci,_from_C2RMF_retouched.jpg"}$q$::jsonb);
