-- Heads Up's seed deck: 180 hand-picked cards over 12 topics, each one clear thing a family room can act out or
-- describe and guess in a minute (no real private people, nothing obscure). The topics match the lobby's interest
-- chips; AI-built decks for other interests join the bank in slice 6b. All family-rated and known everywhere.

insert into content.headsup_cards (topic, card) values
  ('general', 'Umbrella'),
  ('general', 'Toothbrush'),
  ('general', 'Birthday cake'),
  ('general', 'Selfie'),
  ('general', 'Traffic jam'),
  ('general', 'Alarm clock'),
  ('general', 'Rainbow'),
  ('general', 'Sunglasses'),
  ('general', 'Pillow fight'),
  ('general', 'Snowman'),
  ('general', 'Treasure map'),
  ('general', 'Paper plane'),
  ('general', 'Roller coaster'),
  ('general', 'Hide and seek'),
  ('general', 'Fireworks'),
  ('movies', 'Titanic'),
  ('movies', 'The Lion King'),
  ('movies', 'Harry Potter'),
  ('movies', 'Spider-Man'),
  ('movies', 'Frozen'),
  ('movies', 'Jurassic Park'),
  ('movies', 'Star Wars'),
  ('movies', 'Toy Story'),
  ('movies', 'Avengers'),
  ('movies', 'Finding Nemo'),
  ('movies', 'Shrek'),
  ('movies', 'James Bond'),
  ('movies', 'Batman'),
  ('movies', 'Minions'),
  ('movies', 'Jaws'),
  ('bollywood', 'Shah Rukh Khan'),
  ('bollywood', 'Amitabh Bachchan'),
  ('bollywood', 'Sholay'),
  ('bollywood', 'Lagaan'),
  ('bollywood', '3 Idiots'),
  ('bollywood', 'Dilwale Dulhania Le Jayenge'),
  ('bollywood', 'Deepika Padukone'),
  ('bollywood', 'Aamir Khan'),
  ('bollywood', 'Salman Khan'),
  ('bollywood', 'Priyanka Chopra'),
  ('bollywood', 'Kabhi Khushi Kabhie Gham'),
  ('bollywood', 'Dangal'),
  ('bollywood', 'RRR'),
  ('bollywood', 'Baahubali'),
  ('bollywood', 'Hrithik Roshan'),
  ('cricket', 'Sachin Tendulkar'),
  ('cricket', 'Virat Kohli'),
  ('cricket', 'MS Dhoni'),
  ('cricket', 'Sixer'),
  ('cricket', 'Hat-trick'),
  ('cricket', 'Wicket keeper'),
  ('cricket', 'IPL'),
  ('cricket', 'World Cup'),
  ('cricket', 'Duck'),
  ('cricket', 'Umpire'),
  ('cricket', 'Run out'),
  ('cricket', 'Rohit Sharma'),
  ('cricket', 'Spin bowler'),
  ('cricket', 'Super over'),
  ('cricket', 'Test match'),
  ('food', 'Biryani'),
  ('food', 'Pizza'),
  ('food', 'Samosa'),
  ('food', 'Pani puri'),
  ('food', 'Butter chicken'),
  ('food', 'Masala dosa'),
  ('food', 'Ice cream'),
  ('food', 'Chocolate'),
  ('food', 'Popcorn'),
  ('food', 'Sushi'),
  ('food', 'Mango'),
  ('food', 'Chai'),
  ('food', 'Gulab jamun'),
  ('food', 'Noodles'),
  ('food', 'Burger'),
  ('animals', 'Elephant'),
  ('animals', 'Giraffe'),
  ('animals', 'Penguin'),
  ('animals', 'Kangaroo'),
  ('animals', 'Peacock'),
  ('animals', 'Tiger'),
  ('animals', 'Octopus'),
  ('animals', 'Monkey'),
  ('animals', 'Crocodile'),
  ('animals', 'Butterfly'),
  ('animals', 'Camel'),
  ('animals', 'Dolphin'),
  ('animals', 'Owl'),
  ('animals', 'Panda'),
  ('animals', 'Snail'),
  ('music', 'Guitar'),
  ('music', 'Drums'),
  ('music', 'Karaoke'),
  ('music', 'A. R. Rahman'),
  ('music', 'Lata Mangeshkar'),
  ('music', 'Michael Jackson'),
  ('music', 'Taylor Swift'),
  ('music', 'The Beatles'),
  ('music', 'Violin'),
  ('music', 'Headphones'),
  ('music', 'Microphone'),
  ('music', 'Piano'),
  ('music', 'Arijit Singh'),
  ('music', 'Beyonce'),
  ('music', 'Dance floor'),
  ('sports', 'Football'),
  ('sports', 'Olympics'),
  ('sports', 'Tennis'),
  ('sports', 'Basketball'),
  ('sports', 'Swimming'),
  ('sports', 'Marathon'),
  ('sports', 'Badminton'),
  ('sports', 'Chess'),
  ('sports', 'Kabaddi'),
  ('sports', 'Boxing'),
  ('sports', 'Skateboard'),
  ('sports', 'Formula One'),
  ('sports', 'Hockey'),
  ('sports', 'Yoga'),
  ('sports', 'Wrestling'),
  ('places', 'Taj Mahal'),
  ('places', 'Eiffel Tower'),
  ('places', 'Mount Everest'),
  ('places', 'Great Wall of China'),
  ('places', 'Goa'),
  ('places', 'Statue of Liberty'),
  ('places', 'Pyramids'),
  ('places', 'Mumbai'),
  ('places', 'London'),
  ('places', 'Sahara Desert'),
  ('places', 'Niagara Falls'),
  ('places', 'Venice'),
  ('places', 'Himalayas'),
  ('places', 'Kerala'),
  ('places', 'Tokyo'),
  ('famous people', 'Mahatma Gandhi'),
  ('famous people', 'Albert Einstein'),
  ('famous people', 'Leonardo da Vinci'),
  ('famous people', 'Mother Teresa'),
  ('famous people', 'APJ Abdul Kalam'),
  ('famous people', 'Cristiano Ronaldo'),
  ('famous people', 'Lionel Messi'),
  ('famous people', 'Usain Bolt'),
  ('famous people', 'Serena Williams'),
  ('famous people', 'Barack Obama'),
  ('famous people', 'Charlie Chaplin'),
  ('famous people', 'Malala Yousafzai'),
  ('famous people', 'Neil Armstrong'),
  ('famous people', 'Elon Musk'),
  ('famous people', 'Oprah Winfrey'),
  ('science', 'Volcano'),
  ('science', 'Rocket'),
  ('science', 'Magnet'),
  ('science', 'Rainforest'),
  ('science', 'Robot'),
  ('science', 'Dinosaur'),
  ('science', 'Telescope'),
  ('science', 'Lightning'),
  ('science', 'Moon landing'),
  ('science', 'Gravity'),
  ('science', 'Microscope'),
  ('science', 'Black hole'),
  ('science', 'Earthquake'),
  ('science', 'Solar system'),
  ('science', 'DNA'),
  ('tv & cartoons', 'Tom and Jerry'),
  ('tv & cartoons', 'Mickey Mouse'),
  ('tv & cartoons', 'Doraemon'),
  ('tv & cartoons', 'Chhota Bheem'),
  ('tv & cartoons', 'SpongeBob'),
  ('tv & cartoons', 'Pikachu'),
  ('tv & cartoons', 'Scooby-Doo'),
  ('tv & cartoons', 'Mr. Bean'),
  ('tv & cartoons', 'Peppa Pig'),
  ('tv & cartoons', 'Shinchan'),
  ('tv & cartoons', 'The Simpsons'),
  ('tv & cartoons', 'Motu Patlu'),
  ('tv & cartoons', 'Popeye'),
  ('tv & cartoons', 'Bugs Bunny'),
  ('tv & cartoons', 'Dora the Explorer')
on conflict do nothing;
